-- ============================================================================
-- ADVERTENCIA DE SEGURIDAD CLÍNICA:
-- Este seed debe ser revisado y validado por la Dra. Carwin Silva (asesora clínica)
-- antes de uso en producción. Un vademécum con datos incorrectos genera mal matching
-- y consecuencias clínicas para los pacientes.
-- ============================================================================

BEGIN;

-- Limpieza preventiva
DELETE FROM public.medication_catalog;

INSERT INTO public.medication_catalog (inn, concentration, pharmaceutical_form, therapeutic_class, is_controlled) VALUES
-- Antibióticos
('Amoxicilina', '250 mg', 'cápsula', 'Antibiótico', false),
('Amoxicilina', '500 mg', 'cápsula', 'Antibiótico', false),
('Amoxicilina', '250 mg/5 ml', 'suspensión', 'Antibiótico', false),
('Amoxicilina', '875 mg', 'comprimido', 'Antibiótico', false),
('Amoxicilina+Ácido clavulánico', '500 mg+125 mg', 'comprimido', 'Antibiótico', false),
('Amoxicilina+Ácido clavulánico', '875 mg+125 mg', 'comprimido', 'Antibiótico', false),
('Amoxicilina+Ácido clavulánico', '250 mg+62.5 mg/5 ml', 'suspensión', 'Antibiótico', false),
('Azitromicina', '500 mg', 'comprimido', 'Antibiótico', false),
('Azitromicina', '200 mg/5 ml', 'suspensión', 'Antibiótico', false),
('Cefalexina', '500 mg', 'cápsula', 'Antibiótico', false),
('Cefalexina', '250 mg/5 ml', 'suspensión', 'Antibiótico', false),
('Ciprofloxacino', '500 mg', 'comprimido', 'Antibiótico', false),
('Ciprofloxacino', '750 mg', 'comprimido', 'Antibiótico', false),
('Claritromicina', '500 mg', 'comprimido', 'Antibiótico', false),
('Claritromicina', '250 mg/5 ml', 'suspensión', 'Antibiótico', false),
('Doxiciclina', '100 mg', 'cápsula', 'Antibiótico', false),
('Metronidazol', '500 mg', 'comprimido', 'Antibiótico', false),
('Metronidazol', '250 mg/5 ml', 'suspensión', 'Antibiótico', false),
('Trimetoprima+Sulfametoxazol', '80 mg+400 mg', 'comprimido', 'Antibiótico', false),
('Trimetoprima+Sulfametoxazol', '160 mg+800 mg', 'comprimido', 'Antibiótico', false),
('Trimetoprima+Sulfametoxazol', '40 mg+200 mg/5 ml', 'suspensión', 'Antibiótico', false),
('Clindamicina', '300 mg', 'cápsula', 'Antibiótico', false),
('Clindamicina', '600 mg', 'ampolla', 'Antibiótico', false),
('Ampicilina', '500 mg', 'cápsula', 'Antibiótico', false),
('Ampicilina', '1 g', 'vial', 'Antibiótico', false),
('Penicilina G benzatínica', '1.200.000 UI', 'vial', 'Antibiótico', false),
('Penicilina G benzatínica', '2.400.000 UI', 'vial', 'Antibiótico', false),
('Nitrofurantoína', '100 mg', 'cápsula', 'Antibiótico', false),
('Nitrofurantoína', '25 mg/5 ml', 'suspensión', 'Antibiótico', false),

-- Analgésicos / AINES / Antipiréticos
('Paracetamol (Acetaminofén)', '500 mg', 'comprimido', 'Analgésico', false),
('Paracetamol (Acetaminofén)', '650 mg', 'comprimido', 'Analgésico', false),
('Paracetamol (Acetaminofén)', '120 mg/5 ml', 'jarabe', 'Analgésico', false),
('Paracetamol (Acetaminofén)', '80 mg/ml', 'gotas', 'Analgésico', false),
('Ibuprofeno', '400 mg', 'comprimido', 'AINES', false),
('Ibuprofeno', '600 mg', 'comprimido', 'AINES', false),
('Ibuprofeno', '800 mg', 'comprimido', 'AINES', false),
('Ibuprofeno', '100 mg/5 ml', 'suspensión', 'AINES', false),
('Diclofenaco sódico', '50 mg', 'comprimido', 'AINES', false),
('Diclofenaco sódico', '75 mg', 'ampolla', 'AINES', false),
('Diclofenaco sódico', '1%', 'gel', 'AINES', false),
('Ketoprofeno', '100 mg', 'comprimido', 'AINES', false),
('Ketoprofeno', '100 mg', 'ampolla', 'AINES', false),
('Naproxeno', '250 mg', 'comprimido', 'AINES', false),
('Naproxeno', '500 mg', 'comprimido', 'AINES', false),
('Ácido acetilsalicílico', '100 mg', 'comprimido', 'Antiagregante plaquetario', false),
('Ácido acetilsalicílico', '500 mg', 'comprimido', 'AINES', false),
('Ketorolaco', '10 mg', 'comprimido', 'AINES', false),
('Ketorolaco', '30 mg', 'ampolla', 'AINES', false),
('Meloxicam', '7.5 mg', 'comprimido', 'AINES', false),
('Meloxicam', '15 mg', 'comprimido', 'AINES', false),

-- Antihipertensivos / Cardiovascular
('Losartán potásico', '50 mg', 'comprimido', 'Antihipertensivo', false),
('Losartán potásico', '100 mg', 'comprimido', 'Antihipertensivo', false),
('Valsartán', '80 mg', 'comprimido', 'Antihipertensivo', false),
('Valsartán', '160 mg', 'comprimido', 'Antihipertensivo', false),
('Enalapril', '10 mg', 'comprimido', 'Antihipertensivo', false),
('Enalapril', '20 mg', 'comprimido', 'Antihipertensivo', false),
('Lisinopril', '10 mg', 'comprimido', 'Antihipertensivo', false),
('Lisinopril', '20 mg', 'comprimido', 'Antihipertensivo', false),
('Amlodipino', '5 mg', 'comprimido', 'Antihipertensivo', false),
('Amlodipino', '10 mg', 'comprimido', 'Antihipertensivo', false),
('Hidroclorotiazida', '12.5 mg', 'comprimido', 'Diurético', false),
('Hidroclorotiazida', '25 mg', 'comprimido', 'Diurético', false),
('Atenolol', '50 mg', 'comprimido', 'Beta-bloqueante', false),
('Atenolol', '100 mg', 'comprimido', 'Beta-bloqueante', false),
('Metoprolol', '50 mg', 'comprimido', 'Beta-bloqueante', false),
('Metoprolol', '100 mg', 'comprimido', 'Beta-bloqueante', false),
('Carvedilol', '6.25 mg', 'comprimido', 'Beta-bloqueante', false),
('Carvedilol', '12.5 mg', 'comprimido', 'Beta-bloqueante', false),
('Carvedilol', '25 mg', 'comprimido', 'Beta-bloqueante', false),
('Furosemida', '40 mg', 'comprimido', 'Diurético', false),
('Furosemida', '20 mg', 'ampolla', 'Diurético', false),
('Espironolactona', '25 mg', 'comprimido', 'Diurético', false),
('Espironolactona', '100 mg', 'comprimido', 'Diurético', false),
('Clopidogrel', '75 mg', 'comprimido', 'Antiagregante plaquetario', false),
('Atorvastatina', '10 mg', 'comprimido', 'Hipolipemiante', false),
('Atorvastatina', '20 mg', 'comprimido', 'Hipolipemiante', false),
('Atorvastatina', '40 mg', 'comprimido', 'Hipolipemiante', false),
('Simvastatina', '20 mg', 'comprimido', 'Hipolipemiante', false),
('Simvastatina', '40 mg', 'comprimido', 'Hipolipemiante', false),
('Rosuvastatina', '10 mg', 'comprimido', 'Hipolipemiante', false),
('Rosuvastatina', '20 mg', 'comprimido', 'Hipolipemiante', false),

-- Diabetes / Endocrino
('Metformina', '500 mg', 'comprimido', 'Antidiabético', false),
('Metformina', '850 mg', 'comprimido', 'Antidiabético', false),
('Metformina', '1000 mg', 'comprimido', 'Antidiabético', false),
('Glibenclamida', '5 mg', 'comprimido', 'Antidiabético', false),
('Glimepirida', '2 mg', 'comprimido', 'Antidiabético', false),
('Glimepirida', '4 mg', 'comprimido', 'Antidiabético', false),
('Insulina NPH', '100 UI/ml', 'vial', 'Insulina', false),
('Insulina glargina', '100 UI/ml', 'vial', 'Insulina', false),
('Insulina glargina', '100 UI/ml', 'lapicero', 'Insulina', false),
('Levotiroxina', '25 mcg', 'comprimido', 'Hormona tiroidea', false),
('Levotiroxina', '50 mcg', 'comprimido', 'Hormona tiroidea', false),
('Levotiroxina', '75 mcg', 'comprimido', 'Hormona tiroidea', false),
('Levotiroxina', '100 mcg', 'comprimido', 'Hormona tiroidea', false),

-- Gastrointestinal
('Omeprazol', '20 mg', 'cápsula', 'Gastro protector', false),
('Omeprazol', '40 mg', 'cápsula', 'Gastro protector', false),
('Omeprazol', '40 mg', 'vial', 'Gastro protector', false),
('Esomeprazol', '20 mg', 'comprimido', 'Gastro protector', false),
('Esomeprazol', '40 mg', 'comprimido', 'Gastro protector', false),
('Pantoprazol', '40 mg', 'comprimido', 'Gastro protector', false),
('Ranitidina', '150 mg', 'comprimido', 'Gastro protector', false),
('Ranitidina', '50 mg', 'ampolla', 'Gastro protector', false),
('Metoclopramida', '10 mg', 'comprimido', 'Antiemético', false),
('Metoclopramida', '10 mg', 'ampolla', 'Antiemético', false),
('Metoclopramida', '4 mg/ml', 'gotas', 'Antiemético', false),
('Hioscina (butilbromuro)', '10 mg', 'comprimido', 'Antiespasmódico', false),
('Hioscina (butilbromuro)', '20 mg', 'ampolla', 'Antiespasmódico', false),
('Loperamida', '2 mg', 'comprimido', 'Antidiarreico', false),
('Sales de rehidratación oral', '20.5 g', 'sobre', 'Hidratación', false),
('Lactulosa', '10 g/15 ml', 'jarabe', 'Laxante', false),
('Bisacodilo', '5 mg', 'comprimido', 'Laxante', false),
('Bisacodilo', '10 mg', 'supositorio', 'Laxante', false),

-- Respiratorio / Antialérgicos
('Salbutamol', '100 mcg', 'inhalador', 'Broncodilatador', false),
('Salbutamol', '2 mg/5 ml', 'jarabe', 'Broncodilatador', false),
('Salbutamol', '5 mg/ml', 'solución para nebulizar', 'Broncodilatador', false),
('Beclometasona', '50 mcg', 'inhalador', 'Corticoide inhalado', false),
('Beclometasona', '250 mcg', 'inhalador', 'Corticoide inhalado', false),
('Budesonida', '200 mcg', 'inhalador', 'Corticoide inhalado', false),
('Budesonida', '0.25 mg/ml', 'suspensión para nebulizar', 'Corticoide inhalado', false),
('Loratadina', '10 mg', 'comprimido', 'Antihistamínico', false),
('Loratadina', '5 mg/5 ml', 'jarabe', 'Antihistamínico', false),
('Cetirizina', '10 mg', 'comprimido', 'Antihistamínico', false),
('Cetirizina', '5 mg/5 ml', 'jarabe', 'Antihistamínico', false),
('Cetirizina', '10 mg/ml', 'gotas', 'Antihistamínico', false),
('Desloratadina', '5 mg', 'comprimido', 'Antihistamínico', false),
('Desloratadina', '2.5 mg/5 ml', 'jarabe', 'Antihistamínico', false),
('Montelukast', '4 mg', 'comprimido masticable', 'Antiasmático', false),
('Montelukast', '5 mg', 'comprimido masticable', 'Antiasmático', false),
('Montelukast', '10 mg', 'comprimido', 'Antiasmático', false),
('Ambroxol', '30 mg', 'comprimido', 'Mucolítico', false),
('Ambroxol', '15 mg/5 ml', 'jarabe', 'Mucolítico', false),
('Ambroxol', '30 mg/5 ml', 'jarabe', 'Mucolítico', false),
('Bromhexina', '8 mg', 'comprimido', 'Mucolítico', false),
('Bromhexina', '4 mg/5 ml', 'jarabe', 'Mucolítico', false),

-- Corticoides
('Prednisona', '5 mg', 'comprimido', 'Corticoide sistémico', false),
('Prednisona', '20 mg', 'comprimido', 'Corticoide sistémico', false),
('Prednisona', '50 mg', 'comprimido', 'Corticoide sistémico', false),
('Prednisolona', '5 mg/5 ml', 'jarabe', 'Corticoide sistémico', false),
('Prednisolona', '15 mg/5 ml', 'jarabe', 'Corticoide sistémico', false),
('Dexametasona', '4 mg', 'comprimido', 'Corticoide sistémico', false),
('Dexametasona', '4 mg', 'ampolla', 'Corticoide sistémico', false),
('Dexametasona', '8 mg', 'ampolla', 'Corticoide sistémico', false),
('Betametasona', '4 mg', 'ampolla', 'Corticoide sistémico', false),
('Betametasona', '0.1%', 'crema tópica', 'Corticoide tópico', false),
('Hidrocortisona', '100 mg', 'vial', 'Corticoide sistémico', false),
('Hidrocortisona', '250 mg', 'vial', 'Corticoide sistémico', false),
('Hidrocortisona', '1%', 'crema tópica', 'Corticoide tópico', false),

-- Sistema Nervioso Central / Psiquiatría (No controlados)
('Sertralina', '50 mg', 'comprimido', 'Antidepresivo', false),
('Sertralina', '100 mg', 'comprimido', 'Antidepresivo', false),
('Fluoxetina', '20 mg', 'cápsula', 'Antidepresivo', false),
('Escitalopram', '10 mg', 'comprimido', 'Antidepresivo', false),
('Escitalopram', '20 mg', 'comprimido', 'Antidepresivo', false),
('Amitriptilina', '25 mg', 'comprimido', 'Antidepresivo tricíclico', false),
('Carbamazepina', '200 mg', 'comprimido', 'Anticonvulsivante', false),
('Carbamazepina', '400 mg', 'comprimido', 'Anticonvulsivante', false),
('Carbamazepina', '100 mg/5 ml', 'suspensión', 'Anticonvulsivante', false),
('Ácido valproico', '250 mg', 'cápsula', 'Anticonvulsivante', false),
('Ácido valproico', '500 mg', 'comprimido', 'Anticonvulsivante', false),
('Ácido valproico', '250 mg/5 ml', 'jarabe', 'Anticonvulsivante', false),
('Gabapentina', '300 mg', 'cápsula', 'Antineurálgico', false),
('Gabapentina', '400 mg', 'cápsula', 'Antineurálgico', false),
('Pregabalina', '75 mg', 'cápsula', 'Antineurálgico', false),
('Pregabalina', '150 mg', 'cápsula', 'Antineurálgico', false),

-- Psicotrópicos & Benzodiacepinas (CONTROLADOS)
('Clonazepam', '0.5 mg', 'comprimido', 'Benzodiacepina (Ansiolítico)', true),
('Clonazepam', '2 mg', 'comprimido', 'Benzodiacepina (Ansiolítico)', true),
('Clonazepam', '2.5 mg/ml', 'gotas', 'Benzodiacepina (Ansiolítico)', true),
('Alprazolam', '0.25 mg', 'comprimido', 'Benzodiacepina (Ansiolítico)', true),
('Alprazolam', '0.5 mg', 'comprimido', 'Benzodiacepina (Ansiolítico)', true),
('Alprazolam', '1 mg', 'comprimido', 'Benzodiacepina (Ansiolítico)', true),
('Alprazolam', '2 mg', 'comprimido', 'Benzodiacepina (Ansiolítico)', true),
('Diazepam', '5 mg', 'comprimido', 'Benzodiacepina (Ansiolítico/Miorrelajante)', true),
('Diazepam', '10 mg', 'comprimido', 'Benzodiacepina (Ansiolítico/Miorrelajante)', true),
('Diazepam', '10 mg', 'ampolla', 'Benzodiacepina (Ansiolítico/Miorrelajante)', true),
('Metilfenidato', '10 mg', 'comprimido', 'Psicoestimulante', true),
('Metilfenidato', '20 mg', 'comprimido', 'Psicoestimulante', true),
('Fenobarbital', '100 mg', 'comprimido', 'Anticonvulsivante/Barbitúrico', true),
('Fenobarbital', '200 mg/ml', 'ampolla', 'Anticonvulsivante/Barbitúrico', true),

-- Analgésicos Opioides (CONTROLADOS)
('Tramadol', '50 mg', 'cápsula', 'Opioide menor', true),
('Tramadol', '100 mg', 'ampolla', 'Opioide menor', true),
('Tramadol', '100 mg/ml', 'gotas', 'Opioide menor', true),
('Codeína+Paracetamol', '30 mg+500 mg', 'comprimido', 'Opioide menor combinado', true),
('Morfina', '10 mg', 'comprimido', 'Opioide mayor', true),
('Morfina', '30 mg', 'comprimido', 'Opioide mayor', true),
('Morfina', '10 mg', 'ampolla', 'Opioide mayor', true),

-- Ginecología / Urología
('Fluconazol', '150 mg', 'cápsula', 'Antifúngico', false),
('Fluconazol', '200 mg', 'vial', 'Antifúngico', false),
('Clotrimazol', '100 mg', 'óvulo vaginal', 'Antifúngico', false),
('Clotrimazol', '500 mg', 'óvulo vaginal', 'Antifúngico', false),
('Clotrimazol', '2%', 'crema vaginal', 'Antifúngico', false),
('Ácido fólico', '1 mg', 'comprimido', 'Suplemento vitamínico', false),
('Ácido fólico', '5 mg', 'comprimido', 'Suplemento vitamínico', false),
('Hierro (sulfato ferroso)', '200 mg', 'comprimido', 'Suplemento mineral', false),
('Hierro (sulfato ferroso)', '125 mg/ml', 'gotas', 'Suplemento mineral', false),
('Sildenafil', '50 mg', 'comprimido', 'Disfunción eréctil', false),
('Sildenafil', '100 mg', 'comprimido', 'Disfunción eréctil', false),
('Tamsulosina', '0.4 mg', 'cápsula', 'Hiperplasia prostática', false),

-- Dermatología Tópica
('Mupirocina', '2%', 'pomada tópica', 'Antibiótico tópico', false),
('Ketoconazol', '2%', 'crema tópica', 'Antifúngico tópico', false),
('Ketoconazol', '2%', 'shampoo', 'Antifúngico tópico', false),
('Clotrimazol', '1%', 'crema tópica', 'Antifúngico tópico', false),

-- Oftalmología
('Tobramicina', '0.3%', 'colirio', 'Antibiótico oftálmico', false),
('Cloranfenicol', '0.5%', 'colirio', 'Antibiótico oftálmico', false),
('Lágrimas artificiales', '0.5%', 'colirio', 'Humectante oftálmico', false),
('Lágrimas artificiales', '1%', 'colirio', 'Humectante oftálmico', false),

-- Vitaminas / Suplementos
('Complejo B', '1 tab', 'comprimido', 'Vitamínico', false),
('Complejo B', '2 ml', 'ampolla', 'Vitamínico', false),
('Vitamina C', '500 mg', 'comprimido', 'Vitamínico', false),
('Vitamina C', '1 g', 'comprimido efervescente', 'Vitamínico', false),
('Vitamina D3', '1000 UI', 'cápsula', 'Vitamínico', false),
('Vitamina D3', '2000 UI', 'cápsula', 'Vitamínico', false),
('Vitamina D3', '10000 UI', 'cápsula', 'Vitamínico', false),
('Carbonato de Calcio', '500 mg', 'comprimido', 'Suplemento mineral', false),
('Carbonato de Calcio', '600 mg', 'comprimido', 'Suplemento mineral', false),
('Multivitamínico', '1 tab', 'comprimido', 'Vitamínico', false);

COMMIT;
