-- ==============================================================================
-- MODULE 1: MEDICAL REPORTS
-- ==============================================================================

create table if not exists patient_medical_reports (
  id            uuid primary key default gen_random_uuid(),
  patient_id    uuid not null references auth.users(id) on delete cascade,
  consultation_id uuid references consultation(id) on delete set null,
  title         text not null,
  description   text,
  report_type   text not null check (report_type in (
    'laboratorio',
    'imagen',
    'ecografia',
    'resonancia',
    'rayos_x',
    'tomografia',
    'electrocardiograma',
    'biopsia',
    'otro'
  )),
  file_url      text not null,
  file_name     text not null,
  file_size     bigint,
  file_type     text,
  uploaded_by   uuid references auth.users(id),
  is_shared_with_doctor boolean default true,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- Enable RLS
alter table patient_medical_reports enable row level security;

-- Policies for patient_medical_reports
create policy "Patient can manage their own medical reports"
  on patient_medical_reports for all
  using (patient_id = auth.uid())
  with check (patient_id = auth.uid());

create policy "Doctor can view shared medical reports of their patients"
  on patient_medical_reports for select
  using (
    is_shared_with_doctor = true 
    and exists (
      select 1 from consultation c 
      where c.patient_id = patient_medical_reports.patient_id 
      and c.doctor_id = auth.uid()
    )
  );

-- Function and trigger for updated_at
create or replace function set_updated_at_patient_medical_reports()
returns trigger as $$
begin
  NEW.updated_at = now();
  return NEW;
end;
$$ language plpgsql;

create trigger trigger_set_updated_at_patient_medical_reports
  before update on patient_medical_reports
  for each row execute function set_updated_at_patient_medical_reports();

-- Create medical-reports bucket if not exists
insert into storage.buckets (id, name, public) 
values ('medical-reports', 'medical-reports', false)
on conflict (id) do nothing;

-- Storage policies for medical-reports bucket
create policy "Patient can upload their own medical reports"
  on storage.objects for insert
  with check (
    bucket_id = 'medical-reports' 
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "Patient can update their own medical reports"
  on storage.objects for update
  using (
    bucket_id = 'medical-reports' 
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "Patient can delete their own medical reports"
  on storage.objects for delete
  using (
    bucket_id = 'medical-reports' 
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "Patient can view their own medical reports"
  on storage.objects for select
  using (
    bucket_id = 'medical-reports' 
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- We assume doctors use signed URLs generated by the backend, or we can add a select policy for doctors.
create policy "Doctor can view shared patient medical reports"
  on storage.objects for select
  using (
    bucket_id = 'medical-reports' 
    and exists (
      select 1 from patient_medical_reports pmr
      join consultation c on c.patient_id = pmr.patient_id
      where pmr.file_url like '%' || storage.objects.name || '%'
      and pmr.is_shared_with_doctor = true
      and c.doctor_id = auth.uid()
    )
  );


-- ==============================================================================
-- MODULE 2: POST-CONSULTATION SURVEYS
-- ==============================================================================

-- Definition of surveys
create table if not exists consultation_surveys (
  id          uuid primary key default gen_random_uuid(),
  version     int not null default 1,
  is_active   boolean default true,
  questions   jsonb not null,
  created_at  timestamptz default now()
);

-- Responses per consultation and patient
create table if not exists consultation_survey_responses (
  id              uuid primary key default gen_random_uuid(),
  consultation_id uuid not null references consultation(id) on delete cascade,
  patient_id      uuid not null references auth.users(id) on delete cascade,
  survey_id       uuid not null references consultation_surveys(id),
  answers         jsonb not null,
  dismissed       boolean default false,
  completed_at    timestamptz,
  created_at      timestamptz default now(),
  unique(consultation_id, patient_id)
);

-- Enable RLS
alter table consultation_surveys enable row level security;
alter table consultation_survey_responses enable row level security;

-- Policies for surveys
create policy "Anyone authenticated can view active surveys"
  on consultation_surveys for select
  using (auth.role() = 'authenticated');

-- Policies for survey responses
create policy "Patient can manage their own survey responses"
  on consultation_survey_responses for all
  using (patient_id = auth.uid())
  with check (patient_id = auth.uid());

create policy "Doctor can view aggregate responses for their consultations"
  on consultation_survey_responses for select
  using (
    exists (
      select 1 from consultation c 
      where c.id = consultation_survey_responses.consultation_id 
      and c.doctor_id = auth.uid()
    )
  );

-- Insert the default survey
insert into consultation_surveys (version, is_active, questions)
values (
  1, 
  true, 
  '[
    {
      "id": "satisfaction",
      "type": "rating",
      "label": "¿Cómo calificarías tu experiencia en la consulta?",
      "min": 1,
      "max": 5
    },
    {
      "id": "wait_time",
      "type": "single_choice",
      "label": "¿El tiempo de espera fue razonable?",
      "options": ["Sí, fue puntual", "Esperé un poco", "Esperé demasiado"]
    },
    {
      "id": "would_recommend",
      "type": "boolean",
      "label": "¿Recomendarías a este médico?"
    },
    {
      "id": "comments",
      "type": "text",
      "label": "¿Tienes algún comentario adicional? (opcional)",
      "required": false,
      "max_length": 300
    }
  ]'::jsonb
);

-- Trigger for consultations
create or replace function create_survey_on_consultation_complete()
returns trigger as $$
begin
  if NEW.status = 'completada' and OLD.status != 'completada' then
    insert into consultation_survey_responses
      (consultation_id, patient_id, survey_id, answers)
    select
      NEW.id,
      NEW.patient_id,
      s.id,
      '{}'::jsonb
    from consultation_surveys s
    where s.is_active = true
    order by s.version desc
    limit 1
    on conflict (consultation_id, patient_id) do nothing;
  end if;
  return NEW;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to allow safe re-run
drop trigger if exists trigger_survey_on_complete on consultation;

create trigger trigger_survey_on_complete
after update on consultation
for each row execute function create_survey_on_consultation_complete();
