-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_conversation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_conversation_pkey PRIMARY KEY (id),
  CONSTRAINT fk_aiconv_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id)
);
CREATE TABLE public.appointment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  doctor_id uuid,
  organization_id uuid,
  scheduled_at timestamp with time zone NOT NULL,
  duration_minutes integer DEFAULT 30,
  status text NOT NULL DEFAULT 'SCHEDULED'::text,
  reason text,
  location text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  selected_service jsonb,
  unregistered_patient_id uuid,
  booked_by_patient_id character varying,
  referral_source character varying DEFAULT NULL::character varying,
  created_by_role_user_id uuid,
  created_by_doctor_id uuid,
  office_id text,
  notes text,
  CONSTRAINT appointment_pkey PRIMARY KEY (id),
  CONSTRAINT appointment_created_by_role_user_fkey FOREIGN KEY (created_by_role_user_id) REFERENCES public.consultorio_role_users(id),
  CONSTRAINT appointment_created_by_doctor_id_fkey FOREIGN KEY (created_by_doctor_id) REFERENCES public.users(id),
  CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_appointment_org FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT fk_appointment_unregistered_patient FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  user_name text,
  user_role text,
  organization_id uuid,
  action_type text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  description text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clinic_profile (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  legal_rif text,
  legal_name text NOT NULL,
  trade_name text,
  entity_type text,
  address_fiscal text,
  address_operational text,
  state_province text,
  city_municipality text,
  postal_code text,
  phone_fixed text,
  phone_mobile text,
  contact_email text,
  website text,
  social_facebook text,
  social_instagram text,
  social_linkedin text,
  offices_count integer DEFAULT 0,
  specialties jsonb DEFAULT '[]'::jsonb,
  opening_hours jsonb DEFAULT '[]'::jsonb,
  capacity_per_day integer,
  employees_count integer,
  director_name text,
  admin_name text,
  director_id_number text,
  sanitary_license text,
  liability_insurance_number text,
  bank_name text,
  bank_account_type text,
  bank_account_number text,
  bank_account_owner text,
  currency text,
  payment_methods jsonb DEFAULT '[]'::jsonb,
  billing_series text,
  tax_regime text,
  billing_address text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  location jsonb,
  photos jsonb DEFAULT '[]'::jsonb,
  profile_photo text,
  has_cashea boolean DEFAULT false,
  office_id text,
  CONSTRAINT clinic_profile_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_profile_org_fk FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);
CREATE TABLE public.consultation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid,
  patient_id uuid,
  doctor_id uuid NOT NULL,
  organization_id uuid,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  chief_complaint text,
  diagnosis text,
  notes text,
  vitals jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  medical_record_id uuid,
  unregistered_patient_id uuid,
  report_url text,
  icd11_code character varying,
  icd11_title text,
  CONSTRAINT consultation_pkey PRIMARY KEY (id),
  CONSTRAINT fk_consultation_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_consultation_appointment FOREIGN KEY (appointment_id) REFERENCES public.appointment(id),
  CONSTRAINT fk_consultation_medrec FOREIGN KEY (medical_record_id) REFERENCES public.medicalrecord(id),
  CONSTRAINT consultation_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT fk_consultation_doctor FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.consultation_email_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL UNIQUE,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying]::text[])),
  attempts integer NOT NULL DEFAULT 0,
  scheduled_at timestamp with time zone NOT NULL,
  sent_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT consultation_email_queue_pkey PRIMARY KEY (id),
  CONSTRAINT consultation_email_queue_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultation(id)
);
CREATE TABLE public.consultation_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL,
  file_name text NOT NULL,
  path text NOT NULL,
  url text,
  size bigint,
  content_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT consultation_files_pkey PRIMARY KEY (id),
  CONSTRAINT consultation_files_fk_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultation(id)
);
CREATE TABLE public.consultation_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL UNIQUE,
  patient_id uuid,
  unregistered_patient_id uuid,
  doctor_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  communication_rating character varying NOT NULL CHECK (communication_rating::text = ANY (ARRAY['yes'::character varying, 'no'::character varying, 'maybe'::character varying]::text[])),
  attention_rating character varying NOT NULL CHECK (attention_rating::text = ANY (ARRAY['yes'::character varying, 'no'::character varying, 'maybe'::character varying]::text[])),
  satisfaction_rating character varying NOT NULL CHECK (satisfaction_rating::text = ANY (ARRAY['yes'::character varying, 'no'::character varying, 'maybe'::character varying]::text[])),
  comments text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT consultation_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT consultation_ratings_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultation(id),
  CONSTRAINT consultation_ratings_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT consultation_ratings_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT consultation_ratings_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT consultation_ratings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);
CREATE TABLE public.consultation_share_link (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  created_by uuid,
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  access_count integer DEFAULT 0,
  last_accessed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT consultation_share_link_pkey PRIMARY KEY (id),
  CONSTRAINT fk_share_link_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultation(id),
  CONSTRAINT fk_share_link_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id)
);
CREATE TABLE public.consultorio_role_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  role_id uuid,
  role_user_id uuid,
  user_first_name character varying NOT NULL,
  user_last_name character varying NOT NULL,
  user_identifier character varying NOT NULL,
  action_type character varying NOT NULL,
  module character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id uuid,
  action_details jsonb DEFAULT '{}'::jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consultorio_role_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT consultorio_role_audit_log_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT consultorio_role_audit_log_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.consultorio_roles(id),
  CONSTRAINT consultorio_role_audit_log_role_user_id_fkey FOREIGN KEY (role_user_id) REFERENCES public.consultorio_role_users(id)
);
CREATE TABLE public.consultorio_role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_id uuid NOT NULL,
  module character varying NOT NULL,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consultorio_role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT consultorio_role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.consultorio_roles(id)
);
CREATE TABLE public.consultorio_role_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  identifier character varying NOT NULL,
  email character varying,
  phone character varying,
  is_active boolean DEFAULT true,
  last_access_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  password_hash character varying,
  whatsapp_number text,
  CONSTRAINT consultorio_role_users_pkey PRIMARY KEY (id),
  CONSTRAINT consultorio_role_users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.consultorio_roles(id),
  CONSTRAINT consultorio_role_users_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);
CREATE TABLE public.consultorio_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  created_by_user_id uuid NOT NULL,
  role_name character varying NOT NULL,
  role_description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consultorio_roles_pkey PRIMARY KEY (id),
  CONSTRAINT consultorio_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT consultorio_roles_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.conversation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text,
  organization_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conversation_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cross_org_access_permissions (
  permission_id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  share_diagnoses boolean NOT NULL DEFAULT false,
  share_medications_admin boolean NOT NULL DEFAULT false,
  share_lab_results boolean NOT NULL DEFAULT false,
  share_vital_signs boolean NOT NULL DEFAULT false,
  share_nursing_notes boolean NOT NULL DEFAULT false,
  share_visit_summary boolean NOT NULL DEFAULT true,
  allowed_org_ids ARRAY,
  blocked_org_ids ARRAY,
  last_updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT cross_org_access_permissions_pkey PRIMARY KEY (permission_id),
  CONSTRAINT cross_org_access_permissions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT cross_org_access_permissions_last_updated_by_fkey FOREIGN KEY (last_updated_by) REFERENCES auth.users(id),
  CONSTRAINT cross_org_access_permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT cross_org_access_permissions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.doctor_private_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  patient_id uuid,
  unregistered_patient_id uuid,
  notes text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT doctor_private_notes_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_private_notes_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultation(id),
  CONSTRAINT doctor_private_notes_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT doctor_private_notes_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT doctor_private_notes_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id)
);
CREATE TABLE public.doctor_schedule_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL UNIQUE,
  organization_id uuid NOT NULL,
  consultation_type text NOT NULL DEFAULT 'TURNOS'::text CHECK (consultation_type = ANY (ARRAY['TURNOS'::text, 'ORDEN_LLEGADA'::text])),
  max_patients_per_day integer DEFAULT 20 CHECK (max_patients_per_day > 0 AND max_patients_per_day <= 200),
  shift_config jsonb DEFAULT '{"shifts": [{"id": "morning", "name": "Turno Mañana", "enabled": true}, {"id": "afternoon", "name": "Turno Tarde", "enabled": true}], "enabled": true}'::jsonb,
  offices jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT doctor_schedule_config_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_schedule_config_doctor_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT doctor_schedule_config_org_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);
CREATE TABLE public.facturacion (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL,
  patient_id uuid,
  doctor_id uuid,
  organization_id uuid,
  subtotal numeric NOT NULL DEFAULT 0,
  impuestos numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text,
  tipo_cambio numeric DEFAULT 1,
  billing_series text,
  numero_factura text UNIQUE,
  estado_factura text NOT NULL DEFAULT 'emitida'::text,
  estado_pago text NOT NULL DEFAULT 'pendiente'::text,
  metodo_pago text,
  fecha_emision timestamp with time zone NOT NULL DEFAULT now(),
  fecha_pago timestamp with time zone,
  notas text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  unregistered_patient_id uuid,
  consultation_id uuid,
  ajuste_monto numeric DEFAULT 0,
  razon_ajuste text,
  CONSTRAINT facturacion_pkey PRIMARY KEY (id),
  CONSTRAINT fk_facturacion_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_facturacion_doctor FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT fk_facturacion_org FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT fk_facturacion_appointment FOREIGN KEY (appointment_id) REFERENCES public.appointment(id),
  CONSTRAINT fk_facturacion_unregistered_patient FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT fk_facturacion_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultation(id)
);
CREATE TABLE public.familygroup (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  ownerId uuid NOT NULL,
  maxMembers integer NOT NULL DEFAULT 5,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  updatedAt timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT familygroup_pkey PRIMARY KEY (id),
  CONSTRAINT fk_familygroup_owner FOREIGN KEY (ownerId) REFERENCES public.patient(id)
);
CREATE TABLE public.familygroupmember (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  familyGroupId uuid NOT NULL,
  patientId uuid NOT NULL,
  roleInGroup text,
  addedAt timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT familygroupmember_pkey PRIMARY KEY (id),
  CONSTRAINT fk_fgm_group FOREIGN KEY (familyGroupId) REFERENCES public.familygroup(id),
  CONSTRAINT fk_fgm_patient FOREIGN KEY (patientId) REFERENCES public.patient(id)
);
CREATE TABLE public.invite (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organizationId uuid NOT NULL,
  email text,
  token text NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL DEFAULT 'MEDICO'::"UserRole",
  invitedById uuid,
  used boolean NOT NULL DEFAULT false,
  expiresAt timestamp with time zone NOT NULL,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  cancelledat timestamp with time zone,
  cancelledbyid uuid,
  CONSTRAINT invite_pkey PRIMARY KEY (id),
  CONSTRAINT fk_invite_organization FOREIGN KEY (organizationId) REFERENCES public.organization(id),
  CONSTRAINT fk_invite_invitedby FOREIGN KEY (invitedById) REFERENCES public.users(id)
);
CREATE TABLE public.lab_result (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  consultation_id uuid,
  ordering_provider_id uuid,
  result_type text,
  result jsonb,
  attachments ARRAY DEFAULT ARRAY[]::text[],
  is_critical boolean DEFAULT false,
  reported_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  unregistered_patient_id uuid,
  CONSTRAINT lab_result_pkey PRIMARY KEY (id),
  CONSTRAINT fk_labresult_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultation(id),
  CONSTRAINT lab_result_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id)
);
CREATE TABLE public.lab_result_upload (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid,
  patient_id uuid,
  doctor_id uuid,
  organization_id uuid NOT NULL,
  upload_link_id uuid,
  title text NOT NULL,
  description text,
  result_type text,
  additional_details text,
  attachments jsonb DEFAULT '[]'::jsonb,
  specialist_name text NOT NULL,
  specialist_id_number text NOT NULL,
  specialist_lab_name text NOT NULL,
  specialist_email text,
  specialist_phone text,
  patient_first_name text,
  patient_last_name text,
  patient_id_number text NOT NULL,
  patient_email text,
  patient_phone text,
  status text DEFAULT 'pending'::text,
  is_critical boolean DEFAULT false,
  viewed_by_patient boolean DEFAULT false,
  viewed_by_doctor boolean DEFAULT false,
  approved_at timestamp with time zone,
  approved_by uuid,
  rejected_at timestamp with time zone,
  rejected_by uuid,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_result_upload_pkey PRIMARY KEY (id),
  CONSTRAINT lab_result_upload_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultation(id),
  CONSTRAINT lab_result_upload_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT lab_result_upload_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT lab_result_upload_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT lab_result_upload_upload_link_id_fkey FOREIGN KEY (upload_link_id) REFERENCES public.lab_upload_link(id),
  CONSTRAINT lab_result_upload_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT lab_result_upload_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.users(id)
);
CREATE TABLE public.lab_upload_link (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT lab_upload_link_pkey PRIMARY KEY (id),
  CONSTRAINT lab_upload_link_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT lab_upload_link_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.lab_upload_notification (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lab_result_id uuid NOT NULL,
  recipient_type text NOT NULL,
  recipient_id uuid,
  recipient_email text NOT NULL,
  notification_type text NOT NULL,
  status text DEFAULT 'pending'::text,
  sent_at timestamp with time zone,
  error_message text,
  resend_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lab_upload_notification_pkey PRIMARY KEY (id),
  CONSTRAINT lab_upload_notification_lab_result_id_fkey FOREIGN KEY (lab_result_id) REFERENCES public.lab_result_upload(id),
  CONSTRAINT lab_upload_notification_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id)
);
CREATE TABLE public.medic_profile (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL UNIQUE,
  specialty text,
  private_specialty text,
  photo_url text,
  signature_url text,
  credentials jsonb DEFAULT '{}'::jsonb,
  credit_history jsonb DEFAULT '{}'::jsonb,
  services jsonb DEFAULT '[]'::jsonb,
  availability jsonb DEFAULT '{}'::jsonb,
  notifications jsonb DEFAULT '{"push": false, "email": true, "whatsapp": false}'::jsonb,
  two_factor_enabled boolean DEFAULT false,
  two_factor_secret text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  payment_methods jsonb DEFAULT '[]'::jsonb,
  has_cashea boolean DEFAULT false,
  report_template_url text,
  report_template_name text,
  report_template_text text,
  report_font_family text DEFAULT 'Arial'::text,
  prescription_template_url text,
  prescription_template_name text,
  prescription_template_text text,
  prescription_font_family text DEFAULT 'Arial'::text,
  service_combos jsonb DEFAULT '[]'::jsonb,
  whatsapp_number text,
  whatsapp_message_template text DEFAULT 'Hola {NOMBRE_PACIENTE}, le recordamos su cita el {FECHA} a las {HORA} con el Dr/a {NOMBRE_DOCTORA} en {CLÍNICA}. Por los servicios de:

{SERVICIOS}

por favor confirmar con un "Asistiré" o "No Asistiré"'::text,
  lite_mode boolean DEFAULT false,
  report_templates_by_specialty jsonb,
  CONSTRAINT medic_profile_pkey PRIMARY KEY (id),
  CONSTRAINT fk_medic_profile_doctor FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.medical_report_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  name text NOT NULL DEFAULT 'Informe Genérico'::text,
  logo_url text,
  header_text text,
  footer_text text,
  primary_color text DEFAULT '#0F172A'::text,
  secondary_color text DEFAULT '#3B82F6'::text,
  font_family text DEFAULT 'Arial'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  template_text text,
  CONSTRAINT medical_report_templates_pkey PRIMARY KEY (id),
  CONSTRAINT medical_report_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT medical_report_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);
CREATE TABLE public.medicalaccessgrant (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  revoked_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT medicalaccessgrant_pkey PRIMARY KEY (id),
  CONSTRAINT fk_medical_access_grant_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_medical_access_grant_doctor FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.medicalrecord (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patientId uuid NOT NULL,
  authorId uuid,
  content jsonb NOT NULL,
  attachments ARRAY DEFAULT ARRAY[]::text[],
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT medicalrecord_pkey PRIMARY KEY (id),
  CONSTRAINT fk_medicalrecord_patient FOREIGN KEY (patientId) REFERENCES public.patient(id)
);
CREATE TABLE public.medication (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text UNIQUE,
  name text NOT NULL,
  brand text,
  form text,
  strength text,
  unit text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT medication_pkey PRIMARY KEY (id)
);
CREATE TABLE public.medication_dose (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_item_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  prescription_id uuid NOT NULL,
  taken_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT medication_dose_pkey PRIMARY KEY (id),
  CONSTRAINT fk_medication_dose_prescription_item FOREIGN KEY (prescription_item_id) REFERENCES public.prescription_item(id),
  CONSTRAINT fk_medication_dose_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_medication_dose_doctor FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT fk_medication_dose_prescription FOREIGN KEY (prescription_id) REFERENCES public.prescription(id)
);
CREATE TABLE public.message (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  sender_id uuid,
  recipient_user_id uuid,
  patient_id uuid,
  body text,
  attachments ARRAY DEFAULT ARRAY[]::text[],
  read boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_pkey PRIMARY KEY (id),
  CONSTRAINT fk_message_conv FOREIGN KEY (conversation_id) REFERENCES public.conversation(id),
  CONSTRAINT fk_message_sender FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT fk_message_recipient FOREIGN KEY (recipient_user_id) REFERENCES public.users(id),
  CONSTRAINT fk_message_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id)
);
CREATE TABLE public.notification (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  userId uuid,
  organizationId uuid,
  type text NOT NULL,
  title text,
  message text NOT NULL,
  payload jsonb,
  read boolean NOT NULL DEFAULT false,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nurse_mar_records (
  mar_id uuid NOT NULL DEFAULT gen_random_uuid(),
  queue_id uuid NOT NULL,
  patient_id uuid,
  unregistered_patient_id uuid,
  nurse_id uuid NOT NULL,
  organization_id uuid,
  medication_name text NOT NULL,
  medication_id uuid,
  dose text NOT NULL,
  route text NOT NULL,
  frequency text,
  scheduled_at timestamp with time zone NOT NULL,
  administered_at timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::mar_status_enum,
  omission_reason text,
  prescription_id uuid,
  ordered_by_doctor_id uuid,
  prior_treatment_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT nurse_mar_records_pkey PRIMARY KEY (mar_id),
  CONSTRAINT nurse_mar_records_medication_id_fkey FOREIGN KEY (medication_id) REFERENCES public.medication(id),
  CONSTRAINT nurse_mar_records_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescription(id),
  CONSTRAINT nurse_mar_records_ordered_by_doctor_id_fkey FOREIGN KEY (ordered_by_doctor_id) REFERENCES public.users(id),
  CONSTRAINT nurse_mar_records_prior_treatment_id_fkey FOREIGN KEY (prior_treatment_id) REFERENCES public.patient_prior_treatments(treatment_id),
  CONSTRAINT nurse_mar_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT nurse_mar_records_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT nurse_mar_records_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES public.patients_daily_queue(queue_id),
  CONSTRAINT nurse_mar_records_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT nurse_mar_records_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT nurse_mar_records_nurse_id_fkey FOREIGN KEY (nurse_id) REFERENCES public.nurse_profiles(nurse_profile_id),
  CONSTRAINT nurse_mar_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);
CREATE TABLE public.nurse_procedures (
  procedure_id uuid NOT NULL DEFAULT gen_random_uuid(),
  queue_id uuid NOT NULL,
  patient_id uuid,
  unregistered_patient_id uuid,
  nurse_id uuid NOT NULL,
  organization_id uuid,
  ordered_by_doctor_id uuid,
  procedure_name text NOT NULL,
  procedure_code text,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::procedure_status_enum,
  scheduled_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  outcome text,
  notes text,
  supplies_used jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT nurse_procedures_pkey PRIMARY KEY (procedure_id),
  CONSTRAINT nurse_procedures_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES public.patients_daily_queue(queue_id),
  CONSTRAINT nurse_procedures_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT nurse_procedures_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT nurse_procedures_nurse_id_fkey FOREIGN KEY (nurse_id) REFERENCES public.nurse_profiles(nurse_profile_id),
  CONSTRAINT nurse_procedures_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT nurse_procedures_ordered_by_doctor_id_fkey FOREIGN KEY (ordered_by_doctor_id) REFERENCES public.users(id),
  CONSTRAINT nurse_procedures_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT nurse_procedures_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.nurse_profiles (
  nurse_profile_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  nurse_type USER-DEFINED NOT NULL,
  license_number text NOT NULL UNIQUE,
  license_verified boolean NOT NULL DEFAULT false,
  license_expiry date,
  organization_id uuid,
  specializations ARRAY DEFAULT '{}'::text[],
  can_attend_independently boolean NOT NULL DEFAULT false,
  independent_scope jsonb DEFAULT '{}'::jsonb,
  active_since date DEFAULT CURRENT_DATE,
  status USER-DEFINED NOT NULL DEFAULT 'active'::nurse_status_enum,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT nurse_profiles_pkey PRIMARY KEY (nurse_profile_id),
  CONSTRAINT nurse_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT nurse_profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT nurse_profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT nurse_profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.nurse_shift_reports (
  report_id uuid NOT NULL DEFAULT gen_random_uuid(),
  nurse_id uuid NOT NULL,
  organization_id uuid,
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['shift_report'::text, 'independent_care_report'::text])),
  report_date date NOT NULL DEFAULT CURRENT_DATE,
  shift_start timestamp with time zone,
  shift_end timestamp with time zone,
  patients_count integer DEFAULT 0,
  summary text,
  incidents jsonb DEFAULT '[]'::jsonb,
  pending_tasks jsonb DEFAULT '[]'::jsonb,
  pdf_url text,
  signed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT nurse_shift_reports_pkey PRIMARY KEY (report_id),
  CONSTRAINT nurse_shift_reports_nurse_id_fkey FOREIGN KEY (nurse_id) REFERENCES public.nurse_profiles(nurse_profile_id),
  CONSTRAINT nurse_shift_reports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT nurse_shift_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT nurse_shift_reports_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.nurse_vital_signs (
  vital_id uuid NOT NULL DEFAULT gen_random_uuid(),
  queue_id uuid NOT NULL,
  patient_id uuid,
  unregistered_patient_id uuid,
  nurse_id uuid NOT NULL,
  organization_id uuid,
  bp_systolic integer CHECK (bp_systolic >= 50 AND bp_systolic <= 300),
  bp_diastolic integer CHECK (bp_diastolic >= 20 AND bp_diastolic <= 200),
  heart_rate integer CHECK (heart_rate >= 20 AND heart_rate <= 300),
  respiratory_rate integer CHECK (respiratory_rate >= 4 AND respiratory_rate <= 60),
  temperature_celsius numeric CHECK (temperature_celsius >= 30::numeric AND temperature_celsius <= 45::numeric),
  spo2_percent integer CHECK (spo2_percent >= 50 AND spo2_percent <= 100),
  glucose_mg_dl numeric CHECK (glucose_mg_dl >= 20::numeric AND glucose_mg_dl <= 1000::numeric),
  weight_kg numeric CHECK (weight_kg >= 0.5 AND weight_kg <= 500::numeric),
  height_cm numeric CHECK (height_cm >= 30::numeric AND height_cm <= 250::numeric),
  bmi numeric,
  pain_scale integer CHECK (pain_scale >= 0 AND pain_scale <= 10),
  triage_level USER-DEFINED,
  notes text,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT nurse_vital_signs_pkey PRIMARY KEY (vital_id),
  CONSTRAINT nurse_vital_signs_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES public.patients_daily_queue(queue_id),
  CONSTRAINT nurse_vital_signs_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT nurse_vital_signs_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT nurse_vital_signs_nurse_id_fkey FOREIGN KEY (nurse_id) REFERENCES public.nurse_profiles(nurse_profile_id),
  CONSTRAINT nurse_vital_signs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT nurse_vital_signs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT nurse_vital_signs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organization (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type USER-DEFINED NOT NULL,
  address text,
  contactEmail text NOT NULL,
  phone text,
  specialistCount integer NOT NULL DEFAULT 0,
  planId uuid,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  updatedAt timestamp with time zone NOT NULL DEFAULT now(),
  inviteBaseUrl character varying,
  sede_count integer NOT NULL DEFAULT 1,
  is_custom_quote boolean NOT NULL DEFAULT false,
  CONSTRAINT organization_pkey PRIMARY KEY (id),
  CONSTRAINT fk_organization_plan FOREIGN KEY (planId) REFERENCES public.plan(id)
);
CREATE TABLE public.patient (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firstName text NOT NULL,
  lastName text NOT NULL,
  identifier text,
  dob timestamp with time zone,
  gender text,
  phone text,
  address text,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  updatedAt timestamp with time zone NOT NULL DEFAULT now(),
  blood_type character varying,
  allergies text,
  has_disability boolean DEFAULT false,
  disability text,
  has_elderly_conditions boolean DEFAULT false,
  elderly_conditions text,
  unregistered_patient_id uuid UNIQUE,
  profession text,
  advance_directives jsonb,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  emergency_qr_token text UNIQUE,
  emergency_qr_enabled boolean DEFAULT false,
  CONSTRAINT patient_pkey PRIMARY KEY (id)
);
CREATE TABLE public.patient_origin_records (
  origin_id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  unregistered_patient_id uuid,
  queue_id uuid,
  origin_type USER-DEFINED NOT NULL,
  origin_org_id uuid,
  origin_org_name text,
  origin_org_city text,
  origin_org_country text DEFAULT 'CO'::text,
  last_seen_at_origin date,
  referring_doctor_id uuid,
  referring_doctor_name text,
  referring_specialty text,
  referring_org_name text,
  referring_contact text,
  referral_reason USER-DEFINED,
  referral_notes text,
  referral_document_url text,
  registered_by_nurse_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT patient_origin_records_pkey PRIMARY KEY (origin_id),
  CONSTRAINT patient_origin_records_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES public.patients_daily_queue(queue_id),
  CONSTRAINT patient_origin_records_origin_org_id_fkey FOREIGN KEY (origin_org_id) REFERENCES public.organization(id),
  CONSTRAINT patient_origin_records_referring_doctor_id_fkey FOREIGN KEY (referring_doctor_id) REFERENCES public.users(id),
  CONSTRAINT patient_origin_records_registered_by_nurse_id_fkey FOREIGN KEY (registered_by_nurse_id) REFERENCES public.nurse_profiles(nurse_profile_id),
  CONSTRAINT patient_origin_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT patient_origin_records_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT patient_origin_records_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT patient_origin_records_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id)
);
CREATE TABLE public.patient_prior_treatments (
  treatment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  unregistered_patient_id uuid,
  origin_record_id uuid,
  medication_name text NOT NULL,
  presentation text,
  dose text,
  frequency text,
  route text,
  duration_days integer,
  start_date date,
  end_date date,
  treatment_status USER-DEFINED NOT NULL DEFAULT 'unknown'::prior_treatment_status_enum,
  suspension_reason text,
  treatment_outcome text,
  adverse_reaction_desc text,
  prescribed_by_doctor_id uuid,
  prescribed_by_doctor_name text,
  prescribed_at_org_id uuid,
  prescribed_at_org_name text,
  is_currently_active boolean DEFAULT (treatment_status = 'active'::prior_treatment_status_enum),
  interaction_check_needed boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT patient_prior_treatments_pkey PRIMARY KEY (treatment_id),
  CONSTRAINT patient_prior_treatments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT patient_prior_treatments_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT patient_prior_treatments_origin_record_id_fkey FOREIGN KEY (origin_record_id) REFERENCES public.patient_origin_records(origin_id),
  CONSTRAINT patient_prior_treatments_prescribed_by_doctor_id_fkey FOREIGN KEY (prescribed_by_doctor_id) REFERENCES public.users(id),
  CONSTRAINT patient_prior_treatments_prescribed_at_org_id_fkey FOREIGN KEY (prescribed_at_org_id) REFERENCES public.organization(id),
  CONSTRAINT patient_prior_treatments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT patient_prior_treatments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.patientaccesskey (
  patient_id uuid NOT NULL,
  secret text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT patientaccesskey_pkey PRIMARY KEY (patient_id),
  CONSTRAINT fk_patient_access_key_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id)
);
CREATE TABLE public.patients_daily_queue (
  queue_id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  unregistered_patient_id uuid,
  organization_id uuid,
  assigned_nurse_id uuid,
  assigned_doctor_id uuid,
  appointment_id uuid,
  queue_date date NOT NULL DEFAULT CURRENT_DATE,
  arrival_time timestamp with time zone NOT NULL DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'waiting'::queue_status_enum,
  triage_level USER-DEFINED,
  triage_completed_at timestamp with time zone,
  queue_number integer,
  vital_signs_taken boolean NOT NULL DEFAULT false,
  allergies_flag boolean NOT NULL DEFAULT false,
  chronic_flag boolean NOT NULL DEFAULT false,
  referral_flag boolean NOT NULL DEFAULT false,
  cross_org_history_flag boolean NOT NULL DEFAULT false,
  chief_complaint text,
  triage_notes text,
  nurse_notes text,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT patients_daily_queue_pkey PRIMARY KEY (queue_id),
  CONSTRAINT patients_daily_queue_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT patients_daily_queue_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT patients_daily_queue_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT patients_daily_queue_assigned_nurse_id_fkey FOREIGN KEY (assigned_nurse_id) REFERENCES public.nurse_profiles(nurse_profile_id),
  CONSTRAINT patients_daily_queue_assigned_doctor_id_fkey FOREIGN KEY (assigned_doctor_id) REFERENCES public.users(id),
  CONSTRAINT patients_daily_queue_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointment(id),
  CONSTRAINT patients_daily_queue_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT patients_daily_queue_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.pharmacy_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  medication_id uuid NOT NULL,
  lot text,
  expiry_date date,
  quantity integer NOT NULL DEFAULT 0,
  unit_cost numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pharmacy_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT fk_phinv_org FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT fk_phinv_med FOREIGN KEY (medication_id) REFERENCES public.medication(id)
);
CREATE TABLE public.pharmacy_order (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  supplier_id uuid,
  created_by uuid,
  status text NOT NULL DEFAULT 'PENDING'::text,
  placed_at timestamp with time zone NOT NULL DEFAULT now(),
  expected_delivery timestamp with time zone,
  total_amount numeric DEFAULT 0,
  notes text,
  CONSTRAINT pharmacy_order_pkey PRIMARY KEY (id),
  CONSTRAINT fk_phorder_org FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT fk_phorder_creator FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.pharmacy_order_item (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  medication_id uuid NOT NULL,
  quantity integer NOT NULL,
  unit_cost numeric,
  total_cost numeric,
  CONSTRAINT pharmacy_order_item_pkey PRIMARY KEY (id),
  CONSTRAINT fk_phorderitem_order FOREIGN KEY (order_id) REFERENCES public.pharmacy_order(id),
  CONSTRAINT fk_phorderitem_med FOREIGN KEY (medication_id) REFERENCES public.medication(id)
);
CREATE TABLE public.plan (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  minSpecialists integer NOT NULL DEFAULT 0,
  maxSpecialists integer NOT NULL DEFAULT 0,
  monthlyPrice double precision NOT NULL,
  quarterlyPrice double precision,
  annualPrice double precision,
  description text,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  updatedAt timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT plan_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prescription (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  doctor_id uuid NOT NULL,
  consultation_id uuid,
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  valid_until timestamp with time zone,
  notes text,
  status text NOT NULL DEFAULT 'ACTIVE'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  unregistered_patient_id uuid,
  prescription_url text,
  recipe_text text,
  treatment_plan text,
  CONSTRAINT prescription_pkey PRIMARY KEY (id),
  CONSTRAINT fk_prescription_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_prescription_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultation(id),
  CONSTRAINT fk_prescription_unregistered_patient FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id),
  CONSTRAINT fk_prescription_doctor FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.prescription_dispense (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  pharmacy_id uuid,
  dispensed_by uuid,
  dispensed_at timestamp with time zone,
  status text NOT NULL DEFAULT 'PENDING'::text,
  notes text,
  CONSTRAINT prescription_dispense_pkey PRIMARY KEY (id),
  CONSTRAINT fk_prescdisp_prescription FOREIGN KEY (prescription_id) REFERENCES public.prescription(id),
  CONSTRAINT fk_prescdisp_pharmacy FOREIGN KEY (pharmacy_id) REFERENCES public.organization(id),
  CONSTRAINT fk_prescdisp_user FOREIGN KEY (dispensed_by) REFERENCES public.users(id)
);
CREATE TABLE public.prescription_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  file_name text NOT NULL,
  path text NOT NULL,
  url text,
  size bigint,
  content_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prescription_files_pkey PRIMARY KEY (id),
  CONSTRAINT prescription_files_fk_prescription FOREIGN KEY (prescription_id) REFERENCES public.prescription(id)
);
CREATE TABLE public.prescription_item (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  medication_id uuid,
  name text NOT NULL,
  dosage text,
  form text,
  frequency text,
  duration text,
  quantity integer,
  instructions text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  presentation text,
  CONSTRAINT prescription_item_pkey PRIMARY KEY (id),
  CONSTRAINT fk_prescriptionitem_prescription FOREIGN KEY (prescription_id) REFERENCES public.prescription(id),
  CONSTRAINT fk_prescriptionitem_med FOREIGN KEY (medication_id) REFERENCES public.medication(id)
);
CREATE TABLE public.prescription_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL,
  organization_id uuid,
  name text NOT NULL,
  description text,
  file_path text NOT NULL,
  file_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT prescription_templates_pkey PRIMARY KEY (id),
  CONSTRAINT prescription_templates_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.private_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  sender_type character varying NOT NULL CHECK (sender_type::text = ANY (ARRAY['user'::character varying, 'role_user'::character varying]::text[])),
  receiver_id uuid NOT NULL,
  receiver_type character varying NOT NULL CHECK (receiver_type::text = ANY (ARRAY['user'::character varying, 'role_user'::character varying]::text[])),
  organization_id uuid NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT private_messages_pkey PRIMARY KEY (id),
  CONSTRAINT private_messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);
CREATE TABLE public.role_user_payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_by_role_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT role_user_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT role_user_payment_methods_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT role_user_payment_methods_created_by_role_user_id_fkey FOREIGN KEY (created_by_role_user_id) REFERENCES public.consultorio_role_users(id)
);
CREATE TABLE public.subscription (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organizationId uuid,
  patientId uuid,
  planId uuid,
  stripeSubscriptionId text UNIQUE,
  status USER-DEFINED NOT NULL,
  startDate timestamp with time zone NOT NULL,
  endDate timestamp with time zone,
  planSnapshot jsonb NOT NULL,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  updatedAt timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscription_pkey PRIMARY KEY (id),
  CONSTRAINT fk_subscription_organization FOREIGN KEY (organizationId) REFERENCES public.organization(id),
  CONSTRAINT fk_subscription_patient FOREIGN KEY (patientId) REFERENCES public.patient(id),
  CONSTRAINT fk_subscription_plan FOREIGN KEY (planId) REFERENCES public.plan(id)
);
CREATE TABLE public.subscription_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid,
  payment_method text NOT NULL CHECK (payment_method = ANY (ARRAY['BINANCE'::text, 'PAGO_MOVIL'::text])),
  amount_euros numeric NOT NULL,
  amount_bs numeric,
  exchange_rate numeric,
  binance_id text,
  binance_transaction_hash text,
  payment_mobile_ci text,
  payment_mobile_phone text,
  payment_mobile_bank text,
  payment_reference_number text,
  payment_screenshot_url text,
  organization_name text NOT NULL,
  organization_phone text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'VERIFIED'::text, 'REJECTED'::text])),
  verified_at timestamp with time zone,
  verified_by uuid,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscription_payments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_subscription_payment_organization FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT fk_subscription_payment_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_subscription_payment_verified_by FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.successive_consultation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_consultation_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  organization_id uuid,
  consultation_date timestamp with time zone NOT NULL DEFAULT now(),
  lab_results jsonb DEFAULT '{}'::jsonb,
  results_description text,
  doctor_observations text,
  attachments ARRAY DEFAULT '{}'::text[],
  additional_fields jsonb DEFAULT '{}'::jsonb,
  diagnosis text,
  icd11_code text,
  icd11_title text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT successive_consultation_pkey PRIMARY KEY (id),
  CONSTRAINT fk_successive_consultation_original FOREIGN KEY (original_consultation_id) REFERENCES public.consultation(id),
  CONSTRAINT fk_successive_consultation_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_successive_consultation_doctor FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT fk_successive_consultation_org FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT fk_successive_consultation_created_by FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.successive_consultations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_consultation_id uuid NOT NULL,
  patient_id uuid,
  doctor_id uuid NOT NULL,
  organization_id uuid,
  appointment_id uuid,
  consultation_date timestamp with time zone NOT NULL DEFAULT now(),
  lab_results jsonb DEFAULT '{}'::jsonb,
  results_description text,
  observations text,
  additional_fields jsonb DEFAULT '{}'::jsonb,
  images ARRAY DEFAULT ARRAY[]::text[],
  xrays ARRAY DEFAULT ARRAY[]::text[],
  documents ARRAY DEFAULT ARRAY[]::text[],
  diagnosis text,
  icd11_code text,
  icd11_title text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  unregistered_patient_id uuid,
  CONSTRAINT successive_consultations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_successive_consultation_original FOREIGN KEY (original_consultation_id) REFERENCES public.consultation(id),
  CONSTRAINT fk_successive_consultation_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_successive_consultation_doctor FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT fk_successive_consultation_organization FOREIGN KEY (organization_id) REFERENCES public.organization(id),
  CONSTRAINT fk_successive_consultation_appointment FOREIGN KEY (appointment_id) REFERENCES public.appointment(id),
  CONSTRAINT fk_successive_consultation_unregistered_patient FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id)
);
CREATE TABLE public.superadmin (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  email text,
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  last_login_ip text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT superadmin_pkey PRIMARY KEY (id)
);
CREATE TABLE public.task (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  assigned_to uuid,
  patient_id uuid,
  related_consultation_id uuid,
  due_at timestamp with time zone,
  completed boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  unregistered_patient_id uuid,
  CONSTRAINT task_pkey PRIMARY KEY (id),
  CONSTRAINT fk_task_assigned FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT fk_task_consultation FOREIGN KEY (related_consultation_id) REFERENCES public.consultation(id),
  CONSTRAINT fk_task_creator FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT task_unregistered_patient_id_fkey FOREIGN KEY (unregistered_patient_id) REFERENCES public.unregisteredpatients(id)
);
CREATE TABLE public.unregisteredpatients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  identification text,
  birth_date date,
  sex text CHECK (sex = ANY (ARRAY['M'::text, 'F'::text, 'OTHER'::text])),
  phone text NOT NULL,
  email text,
  address text,
  height_cm numeric,
  weight_kg numeric,
  bmi numeric,
  allergies text,
  chronic_conditions text,
  current_medication text,
  family_history text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  migrated_to_patient_id uuid,
  motive text,
  pain_scale integer CHECK (pain_scale >= 0 AND pain_scale <= 10),
  vital_bp_systolic integer,
  vital_bp_diastolic integer,
  vital_heart_rate integer,
  vital_respiratory_rate integer,
  vital_temperature numeric,
  vital_spo2 integer,
  vital_glucose numeric,
  profession text,
  CONSTRAINT unregisteredpatients_pkey PRIMARY KEY (id),
  CONSTRAINT unregisteredpatients_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.medic_profile(id),
  CONSTRAINT unregisteredpatients_migrated_to_patient_id_fkey FOREIGN KEY (migrated_to_patient_id) REFERENCES public.patient(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  auth_id text,
  session_token text NOT NULL UNIQUE,
  ip_address text,
  user_agent text,
  location_data jsonb,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  last_activity_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  interaction_count integer DEFAULT 0,
  pages_visited ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  name text,
  passwordHash text,
  role USER-DEFINED NOT NULL,
  organizationId uuid,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  updatedAt timestamp with time zone NOT NULL DEFAULT now(),
  patientProfileId uuid UNIQUE,
  authId text,
  used boolean NOT NULL DEFAULT true,
  currency_preference character varying DEFAULT 'USD'::character varying,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user_organization FOREIGN KEY (organizationId) REFERENCES public.organization(id),
  CONSTRAINT fk_user_patientprofile FOREIGN KEY (patientProfileId) REFERENCES public.patient(id)
);